### PR TITLE
OBIP-0004: Posts

### PR DESCRIPTION
**Pull request by drwasho**
Proposal to add posts to the OpenBazaar protocol + link to reference implementation

### CODE REVIEW

**Comment by drwasho** [comment]
Thinking of refactoring this a bit @morebrownies by replacing `reference: {peerId, listings [] }` with just a general purposes `tags []`. That way users can use hashtags, or some symbol to denote a user, or put the slug/hash for a listings in there.

**Comment by drwasho** [comment]
Also I need to fix up the protobuf anyway.

**Comment by morebrownies** [comment]
> Thinking of refactoring this a bit @morebrownies by replacing reference: {peerId, listings [] } with just a general purposes tags []. That way users can use hashtags, or some symbol to denote a user, or put the slug/hash for a listings in there.

hmm do we even need the general purpose tags array? From a UX perspective, it would be easier to enter #hashTags or @handles directly into the `title` or `longForm` field(s). I'm thinking it would function a lot like Twitter.

3rd parties could also scrape the content within the `title` or `longForm` and index based on values found.

Maybe I'm over simplifying?

**Comment by morebrownies** [comment]
I read through the OBIP for the second time now and I love this OBIP so much. I see it leading to 2 great outcomes for OpenBazaar:

1)  It will become easier to share / discover content within the ecosystem of OpenBazaar applications. Having the ability to communicate in app will increase the utility value of OpenBazaar while also increasing overall time spent in app. Shoppers / casual users may use OpenBazaar purely for communication needs and Vendors will have another avenue to engage with their followers. Having more user generated content within the platform is key to the growth of OpenBazaar.

2) OpenBazaar the protocol will also become more attractive to developers. They'll have the ability to build p2p social applications with payments + commerce layered in. This new ability for devs may lead to OpenBazaar powered photo apps spinning up on iOS or Android. 

Looks good overall. I'm sure others can validate the schema a bit closer, but seemed on point to me.

**Comment by drwasho** [comment]
Thanks @morebrownies for the comments!

To your earlier points:

> hmm do we even need the general purpose tags array? From a UX perspective, it would be easier to enter #hashTags or @Handles directly into the title or longForm field(s). I'm thinking it would function a lot like Twitter.

I kinda feel that tags sort just happened to Twitter and Instagram, and they integrated it as seamlessly as they could (battling with the idea of whether or not hashtags should count to the tweet length). If they were to design it from scratch, perhaps they would have had a dedicated space for tags?

But more concretely my reason for adding a dedicated `tags` section is two-fold:

1. I'm sparing a thought for client developers so they don't have to parse titles search for URLs, peerIds, handles, or listings hashes/slugs
2. Makes it easier for curators and influencers to clearly anchor their content to a store or collection of listings
3. `tags` allows users to embed other forms of metadata (i.e. location) without eating into space for content.

**Comment by drwasho** [comment]
Btw this is what the schema for a post looks like with tags:

```
{
    "post": {
        "slug": "test3",
        "vendorID": {
            "peerID": "QmVdst57mJuW8Tr9owADqWmirY5Gao9zZMnbbL4WavKJvB",
            "handle": "",
            "pubkeys": {
                "identity": "CAESIEokc1r9Wfe4IyqA9P/56dO+5W1Hv9eOi2PXdUBDUf5X",
                "bitcoin": "AjjghznFUNeAkgmEdKYOESzj+PXFvVHUv+jbNWWQKkwG"
            },
            "bitcoinSig": "MEQCIAaKg1Cr676NVo7dz1KibSvvhjyrAXQceYakKwYR13+oAiBmAWqIyTWMuMPeVItwPzS1N2SDYeR5H4cD+uxGv1AghQ=="
        },
        "title": "test3",
        "longForm": "This is a test post dawg.",
        "images": [
            {
                "filename": "cat",
                "original": "zb2rhe2o6WbHqcER5VUKsMUbQrmpCC6ihg8qZ4JS9wVgKz9wm",
                "large": "zb2rhmBUB9i7UkfmeD3obJYK3FFS5K8N8QHaUanG8UWLVBHiY",
                "medium": "zb2rhaFhqziCWk1zo5tMRxQEUchfvJFaGG4DY1anEoR4GnYrN",
                "small": "zb2rhbDCeEiTTunugWPaRRKFCfNKUaB7aCR53nrPnMa9usZXY",
                "tiny": "zb2rhgqJDbshwAgPjs7X2h4mDm3V3BpLbp4tFGqkg1LNkg9yV"
            }
        ],
        "tags": [
            "Yo"
        ],
        "timestamp": "2017-10-03T03:17:27.125836681Z"
    },
    "hash": "zb2rhiGehVLbtM6gpDbZ8f6R3r8xsw6hdidpiwZEuYskmnig5",
    "signature": "kX6Cc/8RzUWL7qSpwm8I1ytDGwQQjLshzY571Ejjo3lRZvfY4rOW5ZESLs33Gc330lFGprgRrEBA/ewoPdvFBQ=="
}
```

**Comment by morebrownies** [comment]
> I kinda feel that tags sort just happened to Twitter and Instagram, and they integrated it as seamlessly as they could (battling with the idea of whether or not hashtags should count to the tweet length). If they were to design it from scratch, perhaps they would have had a dedicated space for tags?

No mainstream social tools I can think of utilizes an independent tag input. It seems like tagging is almost always accomplished within the body of text. 

Using github as an example, you can type `#` and a overlay displays allowing you to quickly tag another thread.

screenshot 2017-10-03 09 46 31

Slack utilizes the same UX for tagging channels and users within text as well.

screenshot 2017-10-03 10 34 24

Same goes for Instagram and Twitter (which you mentioned above)

In my opinion, this allows for a much more fluid UX and allows users to write more natural without being required to bounce between multiple inputs. It has also become a well known pattern that people expect within applications.

**Comment by morebrownies** [comment]
> But more concretely my reason for adding a dedicated `tags` section is two-fold:

> 1. I'm sparing a thought for client developers so they don't have to parse titles search for URLs, peerIds, handles, or listings hashes/slugs

It looks like Twitter does the parsing on their side to make it easier on developers. Something we could consider on the server side too: https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/get-statuses-show-id

> 2. Makes it easier for curators and influencers to clearly anchor their content to a store or collection of listings

Not entirely sure how it makes it easier? I would think the opposite approach would easier on users. 

> 3. `tags` allows users to embed other forms of metadata (i.e. location) without eating into space for content.

True, but you're suggesting a longer text input that would support 50,000 char. Is this really a concern? If users are way over the maximum limit of the short text, they could switch to longer text mode. Maybe UIs could adapt automatically to longer text mode without user action required. Have some ideas for this.

**Comment by morebrownies** [comment]
I just took a look at Medium and they do appear to support a independent tag input. This somewhat contradicts my comments above. 

screenshot 2017-10-03 10 51 02

I think i'm in agreement now that the API should include some type of `tags` param. If anything, similar to what Twitter does, the server can auto-populate the value. 

If certain clients want to expose a tag input, the server doesn't need to auto-populate in those scenarios. Maybe keeping it flexible is best.

Would love to hear opinions from others as well.

**Comment by ghost** [comment]
Merged in  b67fa3d. Please open an Issue for further discussion.

**Pull request closed without merging**
