### PR TITLE
OBIP-0005: Classifieds

### PR DESCRIPTION
**Pull request by drwasho**
Proposal to add classfieds to the protocol + link to reference implementation

### CODE REVIEW

**Comment by morebrownies** [comment]
Have you posted the suggested schema for Classifieds @drwasho?

Is it safe to assume the schema is slightly different than a Physical or Digital good? Or, is it the same? For example, Variants, Inventory or Coupons may not be needed on a Classified listing type.

Could the Classified listing type also be used for requests? For example, I see a lot of "Wanted" classifieds on Craigslist, e.g: https://chicago.craigslist.org/nwc/clt/d/wanted-buying-beanie-babies/6290937376.html

**Comment by drwasho** [comment]
@morebrownies the 'classified' listing type has all of the functionality that physical, digital, and service listings have, so the schema is exactly the same as what we're using.

I debate whether or not classifieds should be physical, digital, or service... but then I looked at a number of classifieds examples and they're essentially a generic listing type that can be used for anything. I think that's the right way to go.

I definitely think that classifieds can be used for requests, although I'd like to create something dedicated for requests at some point that potentially smart contracts could interact with.

**Comment by drwasho** [comment]
Forgot to mention that `tags` would be an ideal place to put location data related to a classified.

**Comment by ghost** [comment]
Merged in c438106. Please continue any discussion in an Issue.

**Pull request closed without merging**
