### PR TITLE
Channels

### PR DESCRIPTION
**Pull request by cpacia**

### CODE REVIEW

**Comment by rmisio** [comment]
> This OBIP calls for listing data and user data to be provided in each view which means the only loading that needs to be done is the initial JSON document and images. It would be great to make it so these views do not need to provide the data and instead it could be fetched from IPNS but current IPNS speeds are too slow for this to be feasible. As IPNS optimizations come to fruition this option can be revisted.

Hmmm... giving the user free reign to construct whatever data they want seems really risky.

For example, a channel author can give us a listing with the title `ugly dog face` and then link to a legitmate listing where a model is advertising photos of herself.

Another example is a channel author could represent a listing with a price of 100 as 10. When you click the listing with the intent to buy, you may gloss over the price and not compute the 100 because the 10 you saw earlier is in your mind.

Allowing the channel author complete control of how they represent listings while linking to real listings seem fraught with opportuntites for malisciousness.

Not sure how we would minimize or prevent this?

**Comment by rmisio** [comment]
> onClick and onLoad are endpoints which clients are expected to POST to for data collection purposes. The POST body should contain the loaded page URI for onLoad or the URL of the clicked item for onClick.

Unless I'm misunderstanding this, wouldn't we need user approval before tracking their viewing / clicking habits?

**Comment by rmisio** [comment]
```
{
  "type": "TEXT_VIEW",
  "text": "Welcome to my channel!",
  "Link": "ob://QmYj1ojj3cRKrmkQR3o8KtPqmTbgsZWsgq5grpUpAbjiYx/channel/another_channel_page",
  "size": 28,
  "font": "noto sans",
  "color": "#343434",
  "align": "center"
} 
```

@morebrownies  Do we want to expose fonts and font size to the channel author. Stuff like this gives them a lot of rope and if they're not careful it could result in a really ugly (or broken) layout. It also results in an inconsistent Channel look and feel across the app.

I suppose if we opened up some exta styling to just a headline, that would be one thing, but in theory the channel author could create 50 text views and put them all over the page.

If we did expose text color to them, we'd also need to let them control the background of the page, otherwise their text color might not play well with the background color from the theme.

**Comment by rmisio** [comment]
> A 4 by x grid of listing cards.

I'm not sure I would document this as `4 by X`. I think the amount per row should probably be driven by the client since each client has such unique space constraints.

I think it's fine to leave it generic that the `LISTING_GRID_VIEW` will display listings in a grid, which may be 10 X x on wide screens or 1 by X on mobile.

**Comment by rmisio** [comment]
> The user card equivilent of PaginatedListingView.

hmmm... I don't have the designs in front of me so I don't have the full context, but a few thoughts:

First, do we want to expose paginating to the channel author? Since this is pagination that is expected to be done on the client, would it not be better for the author to just provide as many listings as they feel comfortable and leave it up to individual clients to decide whether they want to paginate or not.

I would think if a channel creator gave a list of 500 user cards, a client would want to paginate that regardless of whether the channel author indicated they wanted that.

It's just another one of those where I question if we're giving the author too much rope.

If we do decide to allow pagination to be controlled by the Channel author, my second thought is, do we need separate non-paginated and paginate-listing types? It seems like the data is so similar that it could be collapsed into one, with pagination applied if some specific properties are present.

**Comment by rmisio** [comment]
Can you give an example Page schema? What would it's relationship be to a Channel schema (instead of Views in the channel, it would have a page or pages...?)?

**Comment by cpacia** [comment]
> Unless I'm misunderstanding this, wouldn't we need user approval before tracking their viewing / clicking habits?

We could definitely ask... though I would expect that would pretty dramatically reduce the participation rate. But if we could get a accurate data on what % of users allow data collection then maybe we could extrapolate for the rest of the users.

**Comment by cpacia** [comment]
> I'm not sure I would document this as 4 by X. I think the amount per row should probably be driven by the client since each client has such unique space constraints.

Yeah x was a bit of a placeholder for discussion. In wolf's designs it's 4x2 which seems fine to me. Also 8 lisitngs would probably be a good amount to swipe around with on mobile.

**Comment by cpacia** [comment]
> hmmm... I don't have the designs in front of me so I don't have the full context, but a few thoughts:

So let me give my thinking here. Most of the other views are really geared towards creating landing pages with a mix of different views to make them look unique. 

But if you're trying to categorize a bunch of listings at some point you just want a page with a bunch of listings that renders very similar to what we have in search. That's the primary purpose of that paginated view. It wouldn't really be used on index page, but maybe if someone clicked on a "comic books" category then we would use it for that. Just a full page of listings with some arrows at the bottom for changing pages. 

I'm thinking this one would differ from the ListingGridView in that this one allows for many listings to be rendered whereas the ListingGridView is just maybe a 4x2 widget with a "see more" button. So for example, we might use the ListingGridView on the home page with the title "New Listings" and when they click "See more" then it takes them to a new page with a single PaginatedListingView that show all new listings (or at least a reasonable amount of them).

**Comment by cpacia** [comment]
> Can you give an example Page schema? What would it's relationship be to a Channel schema (instead of Views in the channel, it would have a page or pages...?)?

I'm probably unclear. I'm proposing every page use the schema defined under the Channel shema (maybe that section could be called Page schema instead). So the client only has one job... take the json and render it. Each page uses the same schema (including the index page), they just might have a different collection of views. The `links` found in the image or category views would trigger the client to load and render a new page when clicked on.

**Comment by rmisio** [comment]
> Yeah x was a bit of a placeholder for discussion. In wolf's designs it's 4x2 which seems fine to me. Also 8 lisitngs would probably be a good amount to swipe around with on mobile.

I meant, I wouldn't even publicize the first number (4 by) because I'd leave it up to the client to decide how to layout the grid, which might be 10 in a row for large desktops or 1 per row for mobile.

**Comment by rmisio** [comment]
> I'm thinking this one would differ from the ListingGridView in that this one allows for many listings to be rendered whereas the ListingGridView is just maybe a 4x2 widget with a "see more" button. 

My thinking is that it shouldn't be a decision of the channel author of whether a grid of listings is or is not paginated or how many listing to show per page.

I think this should be a decision of the client since different clients have different screen constraints as well as being tailored to different bandwidths and hardware.

So, the Channel author just provides the "listing grid view" listing type and then provides a list of listings (which may be 4 with a link to see more -or- may be a list of 500 (which also could include a link to see more if they want)).

The client based on their specific situation would decide how it wants to represent that grid. A mobile device (phone) might put them all in one column and paginate after 8 (if there are that many) whereas a wide desktop may put them in rows of 8 and paginate after 32.

@morebrownies what do you think? (you may want to read my initial comment and Chris's response for full context)

**Comment by cpacia** [comment]
@rmisio that's probably works. My thinking was the GridView would be a combination of a title, listings, and button. But that was before adding a text view. I suppose they could just use a generic ListingView to recreate the same thing and just slap a textview above it.

**Comment by morebrownies** [comment]
```
{
  "type": "TEXT_VIEW",
  "text": "Welcome to my channel!",
  "Link": "ob://QmYj1ojj3cRKrmkQR3o8KtPqmTbgsZWsgq5grpUpAbjiYx/channel/another_channel_page",
  "size": 28,
  "font": "noto sans",
  "color": "#343434",
  "align": "center"
} 
```

> @morebrownies Do we want to expose fonts and font size to the channel author. Stuff like this gives them a lot of rope and if they're not careful it could result in a really ugly (or broken) layout. It also results in an inconsistent Channel look and feel across the app.

My initial thought is we should keep most styling params (fonts, sizes, alignment) outside of the data structure and defer to the clients to choose how to display the data. Clients may be anything from: websites, desktop apps, mobile apps, smart watches, VR, and future devices we're unaware of at the current time. It's going to be next to impossible to carry over the preferred styling across platforms. 

The `font` parameter can especially be problematic as it may introduce licensing issues. For example, a `font` license on a website vs a mobile app typically comes with a different price tag. 

I imagine most clients will ignore styling params provided in the data structure and instead present their own custom UI.

**Comment by morebrownies** [comment]
> Hmmm... giving the user free reign to construct whatever data they want seems really risky.

> For example, a channel author can give us a listing with the title ugly dog face and then link to a legitmate listing where a model is advertising photos of herself.

> Another example is a channel author could represent a listing with a price of 100 as 10. When you click the listing with the intent to buy, you may gloss over the price and not compute the 100 because the 10 you saw earlier is in your mind.

This is true on the web as well. For example, **Google Shopping** curates products found on the web, and presents them in their own UI: https://www.google.com/shopping

Some prices may be outdated and/or it's possible (although unlikely) that Google misrepresents product pricing. 

I agree this is a concern and we should keep an eye on it, but if Channels emerge that purposely confuse consumers, the likelihood of those channels becoming popular is probably pretty slim.

**Comment by morebrownies** [comment]
> I'm not sure I would document this as 4 by X. I think the amount per row should probably be driven by the client since each client has such unique space constraints.

> I think it's fine to leave it generic that the LISTING_GRID_VIEW will display listings in a grid, which may be 10 X x on wide screens or 1 by X on mobile.

Agree with @rmisio on this point. # of listings per row will mostly come down to device/screen size.

I would vote to omit specific grid sizes from the schema and defer to clients on how best to display LISTING_GRID_VIEW.

**Comment by morebrownies** [comment]
> Unless I'm misunderstanding this, wouldn't we need user approval before tracking their viewing / clicking habits?

> We could definitely ask... though I would expect that would pretty dramatically reduce the participation rate. But if we could get a accurate data on what % of users allow data collection then maybe we could extrapolate for the rest of the users.

That's really going to be up to 3rd party developers to decide, right? 

Best practice would be to give users a way to opt out of tracking, but that experience may not be replicated across all 3rd party applications.

**Comment by morebrownies** [comment]
> So, the Channel author just provides the "listing grid view" listing type and then provides a list of listings (which may be 4 with a link to see more -or- may be a list of 500 (which also could include a link to see more if they want)).

> The client based on their specific situation would decide how it wants to represent that grid. A mobile device (phone) might put them all in one column and paginate after 8 (if there are that many) whereas a wide desktop may put them in rows of 8 and paginate after 32.

> @morebrownies what do you think? (you may want to read my initial comment and Chris's response for full context)

Yes, agreed. Commented on this above too.

I think the Schema looks pretty good overall. My main concerns are around including styling in the schema.

I also have some concerns regarding `HBox` and `VBox`. Specifying images to vertically stack on top of each other may work well on some platforms (mobile), but may be overly specific and difficult to work with on desktop/web applications. 

For example, in my channel if I specify a single row of 10 images (or text) to be stacked vertically on each other, that would create a strange experience in the desktop app. 

I wonder if it would be better to modify `ImageView` to support an array of images and ditch `Hbox` and `VBox`? Each 3rd party developer can then decided how best to render the array of images based on available screen real estate.

**Comment by rmisio** [comment]
> That's really going to be up to 3rd party developers to decide, right?

> Best practice would be to give users a way to opt out of tracking, but that experience may not be replicated across all 3rd party applications.

We're not talking about a 3rd party application here. We're talking about a channel that lives in our app and with the proposed structure we would be sending usage data to a 3rd party and, unless the user is on Tor, that usage data would include the user's IP. Seems doing this on a non-opt-in basis is against our core principles and we do nothing similarly anywhere else in the app.

I think we should bring this point up to the larger team.

@SamPatt I'd be curious to know your thoughts regarding this issue. The OBIP proposal here is proposing that every time a listing is clicked in a channel, that "click" is sent back to a url specified by the channel provider and, unless they are on Tor, it would include their IP.

I suppose this is somewhat similar to the "report" button we were talking about on 3rd party search listings, but the difference is in that scenario the user actually has to click "Report" whereas here they just need to click a listing card, which they would do just to view the listing.

Also, the proposal proposes that as soon as you load a channel, it would send that "happening" back to a url provided by the channel author.

**Comment by rmisio** [comment]
> I also have some concerns regarding HBox and VBox. Specifying images to vertically stack on top of each other may work well on some platforms (mobile), but may be overly specific and difficult to work with on desktop/web applications.

> For example, in my channel if I specify a single row of 10 images (or text) to be stacked vertically on each other, that would create a strange experience in the desktop app.

Yeah, I 100% agree with Wolf here. The only reason I didn't flag those is because I hadn't seen the designs and was reserving judgment.

IMHO, styling should not be something that is done by the Channel author. Styling is too dependent on the specific constraints of a client and those constraints vary widely between clients. The channel author should just provide data and the view type.

> I wonder if it would be better to modify ImageView to support an array of images and ditch Hbox and VBox? Each 3rd party developer can then decided how best to render the array of images based on available screen real estate.

Sounds good to me.

**Comment by rmisio** [comment]
> @rmisio that's probably works. My thinking was the GridView would be a combination of a title, listings, and button. But that was before adding a text view.

I think any of the view types should be able to support a title. If it's there the client would know that is a heading for the particular view type and could style it appropriately.

> I suppose they could just use a generic ListingView to recreate the same thing and **just slap a textview above it**.

I wouldn't recommend that because the client won't know that text view is intended to be a heading for the subsequent grid view and the styling of the heading of view type would be different from the styling of some generic "TEXT_VIEW" that I guess could be anywhere on the page.

This brings up another point... @morebrownies Do we even need this generic "TEXT_VIEW"? Would it not be better for any of the view types to just be able to support a "title" attribute and then the client knows that the title is a headline for the view type it's provided with and can style it appropriately?

I'm not seeing the use-case for a channel author needing to put some random text somewhere on the page.

**Comment by morebrownies** [comment]
> The OBIP proposal here is proposing that every time a listing is clicked in a channel, that "click" is sent back to a url specified by the channel provider and, unless they are on Tor, it would include their IP.

To be clear, it's proposing that Channel creators will have the _option_ to include a link for onClick tracking events. It will be up to each application dev teams to decide if they want to incorporate this functionality into their client, or not. 

Using the OpenBazaar client as an example, I would imagine we would inform the user of tracking within Channels and give them a way to opt-out. I can dig into best practices regarding tracking, but probably best not to focus this discussion to be overly specific about the OpenBazaar client. We can work out those details later when we're ready to implement it. 

At this time, we should decide if optionally supporting onClick tracking callbacks is generally a good idea / useful or not.

**Comment by morebrownies** [comment]
> I think any of the view types should be able to support a title. If it's there the client would know that is a heading for the particular view type and could style it appropriately.

I agree. `title` param should be associated to each view type.

**Comment by morebrownies** [comment]
> This brings up another point... @morebrownies Do we even need this generic "TEXT_VIEW"? Would it not be better for any of the view types to just be able to support a "title" attribute and then the client knows that the title is a headline for the view type it's provided with and can style it appropriately?

> I'm not seeing the use-case for a channel author needing to put some random text somewhere on the page.

Assuming `title` is a param for each view type, I don't see a need for having independent TEXT_VIEW at this time.

**Comment by rmisio** [comment]
> At this time, we should decide if optionally supporting onClick tracking callbacks is generally a good idea / useful or not.

Fair enough. I have no problem it being a part of the spec as long as it's made clear that it is up to the client to honor this or not and we would have a discussion on whether the desktop client should honor this.

**Comment by ghost** [comment]
This OBIP was merged in https://github.com/OpenBazaar/obips/commit/1997edd003810e1dfde5b5d08a92b8baf2ff11a8.

Please move discussion to an Issue.

**Pull request closed without merging**
